import {
  Dumbbell,
  Shirt,
  Maximize,
  Box,
  Scissors,
  Layers,
  Footprints,
  Droplets,
} from "lucide-react";

export interface Product {
  id: string;
  name: string;
  price: number;
  image: string;
  category: string;
  brand: string;
  description: string;
  badge?: string;
  rating?: number;
}

export const allProducts: Product[] = [
  // Shorts Deportivos
  {
    id: "short-deportivo-pro",
    name: "Short Deportivo Pro",
    price: 28.0,
    image: "/athletic-shorts-performance-mens.jpg",
    category: "Shorts Deportivos",
    brand: "", // Updated to include brand field
    description: "Comodidad y estilo para tu entrenamiento",
    badge: "Oferta",
    rating: 4,
  },
  {
    id: "short-running-elite",
    name: "Short Running Elite",
    price: 32.0,
    image: "/men-s-athletic-shorts-sportswear.jpg",
    category: "Shorts Deportivos",
    brand: "", // Updated to include brand field
    description: "Perfecto para correr y entrenar",
    rating: 5,
  },
  {
    id: "short-nike-pro-1",
    name: "Nike Pro Flex Short",
    price: 35.0,
    image: "/athletic-shorts-performance-mens.jpg",
    category: "Shorts Deportivos",
    brand: "Nike",
    description: "Short deportivo de alto rendimiento con tecnología Dri-FIT",
    badge: "Más Vendido",
    rating: 5,
  },
  {
    id: "short-adidas-training",
    name: "Adidas Training Short",
    price: 32.0,
    image: "/men-s-athletic-shorts-sportswear.jpg",
    category: "Shorts Deportivos",
    brand: "Adidas",
    description: "Perfecto para entrenamientos intensos",
    rating: 5,
  },
  {
    id: "short-under-armour",
    name: "Under Armour Speed Short",
    price: 38.0,
    image: "/athletic-shorts-performance-mens.jpg",
    category: "Shorts Deportivos",
    brand: "Under Armour",
    description: "Ligereza y velocidad en cada movimiento",
    rating: 4,
  },
  {
    id: "short-puma-active",
    name: "Puma Active Short",
    price: 28.0,
    image: "/men-s-athletic-shorts-sportswear.jpg",
    category: "Shorts Deportivos",
    brand: "Puma",
    description: "Estilo deportivo para el día a día",
    badge: "Oferta",
    rating: 4,
  },

  // Franelas
  {
    id: "franela-premium-oversize",
    name: "Franela Premium Oversize",
    price: 35.0,
    image: "/oversized-premium-tshirt-black.jpg",
    category: "Franelas",
    brand: "", // Updated to include brand field
    description: "Estilo urbano y comodidad premium",
    badge: "Más Vendido",
    rating: 5,
  },
  {
    id: "franela-basica-blanca",
    name: "Franela Básica Blanca",
    price: 25.0,
    image: "/men-s-t-shirts-casual-cotton-tees.jpg",
    category: "Franelas",
    brand: "", // Updated to include brand field
    description: "El básico esencial de tu guardarropa",
    rating: 5,
  },
  {
    id: "franela-nike-basic",
    name: "Nike Sportswear Tee",
    price: 28.0,
    image: "/men-s-t-shirts-casual-cotton-tees.jpg",
    category: "Franelas",
    brand: "Nike",
    description: "Camiseta básica de algodón premium",
    rating: 5,
  },
  {
    id: "franela-adidas-essentials",
    name: "Adidas Essentials Tee",
    price: 25.0,
    image: "/oversized-premium-tshirt-black.jpg",
    category: "Franelas",
    brand: "Adidas",
    description: "Estilo casual para uso diario",
    rating: 5,
  },
  {
    id: "franela-puma-classic",
    name: "Puma Classic Crew Tee",
    price: 22.0,
    image: "/men-s-t-shirts-casual-cotton-tees.jpg",
    category: "Franelas",
    brand: "Puma",
    description: "Diseño clásico atemporal",
    badge: "Oferta",
    rating: 4,
  },
  {
    id: "franela-reebok-performance",
    name: "Reebok Performance Tee",
    price: 26.0,
    image: "/oversized-premium-tshirt-black.jpg",
    category: "Franelas",
    brand: "Reebok",
    description: "Tela técnica que absorbe la humedad",
    rating: 4,
  },

  // Oversize
  {
    id: "oversize-urban-negro",
    name: "Oversize Urban Negro",
    price: 38.0,
    image: "/oversized-men-s-streetwear-clothing.jpg",
    category: "Oversize",
    brand: "", // Updated to include brand field
    description: "La tendencia urbana del momento",
    badge: "Nuevo",
    rating: 5,
  },
  {
    id: "oversize-nike-urban",
    name: "Nike Urban Oversize Tee",
    price: 40.0,
    image: "/oversized-men-s-streetwear-clothing.jpg",
    category: "Oversize",
    brand: "Nike",
    description: "Estilo urbano con corte holgado",
    badge: "Nuevo",
    rating: 5,
  },
  {
    id: "oversize-adidas-street",
    name: "Adidas Street Oversize",
    price: 38.0,
    image: "/oversized-premium-tshirt-black.jpg",
    category: "Oversize",
    brand: "Adidas",
    description: "Tendencia streetwear premium",
    rating: 5,
  },
  {
    id: "oversize-stussy-classic",
    name: "Stüssy Oversize Classic",
    price: 45.0,
    image: "/oversized-men-s-streetwear-clothing.jpg",
    category: "Oversize",
    brand: "Stüssy",
    description: "Icónico diseño de marca urbana",
    badge: "Premium",
    rating: 5,
  },
  {
    id: "oversize-carhartt-wip",
    name: "Carhartt WIP Oversize Tee",
    price: 42.0,
    image: "/oversized-premium-tshirt-black.jpg",
    category: "Oversize",
    brand: "Carhartt",
    description: "Calidad workwear en estilo urbano",
    rating: 5,
  },

  // Box Fit
  {
    id: "box-fit-elegante",
    name: "Box Fit Elegante",
    price: 42.0,
    image: "/box-fit-men-s-shirt-structured-style.jpg",
    category: "Box Fit",
    brand: "", // Updated to include brand field
    description: "Corte moderno y estructura perfecta",
    rating: 5,
  },
  {
    id: "boxfit-zara-structured",
    name: "Zara Structured Box Fit",
    price: 42.0,
    image: "/box-fit-men-s-shirt-structured-style.jpg",
    category: "Box Fit",
    brand: "Zara",
    description: "Corte estructurado elegante",
    rating: 5,
  },
  {
    id: "boxfit-hm-modern",
    name: "H&M Modern Box Fit Shirt",
    price: 38.0,
    image: "/box-fit-men-s-shirt-structured-style.jpg",
    category: "Box Fit",
    brand: "H&M",
    description: "Estilo moderno versátil",
    badge: "Más Vendido",
    rating: 4,
  },
  {
    id: "boxfit-uniqlo-premium",
    name: "Uniqlo Premium Box Fit",
    price: 45.0,
    image: "/box-fit-men-s-shirt-structured-style.jpg",
    category: "Box Fit",
    brand: "Uniqlo",
    description: "Calidad japonesa excepcional",
    rating: 5,
  },

  // Jeans
  {
    id: "jeans-slim-fit-oscuro",
    name: "Jeans Slim Fit Oscuro",
    price: 65.0,
    image: "/dark-slim-fit-jeans-mens.jpg",
    category: "Jeans",
    brand: "", // Updated to include brand field
    description: "Denim de calidad premium",
    badge: "Nuevo",
    rating: 5,
  },
  {
    id: "jeans-levis-511",
    name: "Levi's 511 Slim Fit",
    price: 75.0,
    image: "/men-s-premium-denim-jeans-blue.jpg",
    category: "Jeans",
    brand: "Levi's",
    description: "El jean slim fit por excelencia",
    badge: "Clásico",
    rating: 5,
  },
  {
    id: "jeans-diesel-sleenker",
    name: "Diesel Sleenker Skinny",
    price: 95.0,
    image: "/dark-slim-fit-jeans-mens.jpg",
    category: "Jeans",
    brand: "Diesel",
    description: "Denim italiano premium",
    badge: "Premium",
    rating: 5,
  },
  {
    id: "jeans-wrangler-classic",
    name: "Wrangler Classic Straight",
    price: 58.0,
    image: "/men-s-premium-denim-jeans-blue.jpg",
    category: "Jeans",
    brand: "Wrangler",
    description: "Estilo americano auténtico",
    rating: 5,
  },
  {
    id: "jeans-gap-vintage",
    name: "GAP Vintage Slim",
    price: 65.0,
    image: "/dark-slim-fit-jeans-mens.jpg",
    category: "Jeans",
    brand: "GAP",
    description: "Acabado vintage moderno",
    badge: "Nuevo",
    rating: 4,
  },

  // Boxer Interiores
  {
    id: "boxer-comfort-pack",
    name: "Boxer Comfort Pack x3",
    price: 35.0,
    image: "/men-s-boxer-briefs-underwear.jpg",
    category: "Boxer Interiores",
    brand: "", // Updated to include brand field
    description: "Comodidad interior excepcional",
    rating: 5,
  },
  {
    id: "boxer-calvin-klein-pack",
    name: "Calvin Klein Pack x3",
    price: 45.0,
    image: "/men-s-boxer-briefs-underwear.jpg",
    category: "Boxer Interiores",
    brand: "Calvin Klein",
    description: "Comodidad premium todo el día",
    badge: "Premium",
    rating: 5,
  },
  {
    id: "boxer-tommy-hilfiger",
    name: "Tommy Hilfiger Pack x3",
    price: 42.0,
    image: "/men-s-boxer-briefs-underwear.jpg",
    category: "Boxer Interiores",
    brand: "Tommy Hilfiger",
    description: "Estilo clásico americano",
    rating: 5,
  },
  {
    id: "boxer-hugo-boss",
    name: "Hugo Boss Pack x3",
    price: 48.0,
    image: "/men-s-boxer-briefs-underwear.jpg",
    category: "Boxer Interiores",
    brand: "Hugo Boss",
    description: "Elegancia alemana en ropa interior",
    badge: "Más Vendido",
    rating: 5,
  },
  {
    id: "boxer-hanes-comfort",
    name: "Hanes Comfort Pack x5",
    price: 35.0,
    image: "/men-s-boxer-briefs-underwear.jpg",
    category: "Boxer Interiores",
    brand: "Hanes",
    description: "Máxima comodidad diaria",
    badge: "Oferta",
    rating: 4,
  },

  // Medias Deportivas
  {
    id: "medias-deportivas-pack",
    name: "Medias Deportivas Pack x6",
    price: 22.0,
    image: "/athletic-sports-socks-men-s.jpg",
    category: "Medias Deportivas",
    brand: "", // Updated to include brand field
    description: "Rendimiento y confort",
    rating: 4,
  },
  {
    id: "medias-nike-elite",
    name: "Nike Elite Crew Pack x6",
    price: 28.0,
    image: "/athletic-sports-socks-men-s.jpg",
    category: "Medias Deportivas",
    brand: "Nike",
    description: "Rendimiento profesional",
    badge: "Más Vendido",
    rating: 5,
  },
  {
    id: "medias-adidas-cushioned",
    name: "Adidas Cushioned Pack x6",
    price: 25.0,
    image: "/athletic-sports-socks-men-s.jpg",
    category: "Medias Deportivas",
    brand: "Adidas",
    description: "Acolchado extra para deportes",
    rating: 5,
  },
  {
    id: "medias-puma-performance",
    name: "Puma Performance Pack x6",
    price: 22.0,
    image: "/athletic-sports-socks-men-s.jpg",
    category: "Medias Deportivas",
    brand: "Puma",
    description: "Ideal para entrenamientos intensos",
    badge: "Oferta",
    rating: 4,
  },
  {
    id: "medias-under-armour",
    name: "Under Armour Tech Pack x6",
    price: 26.0,
    image: "/athletic-sports-socks-men-s.jpg",
    category: "Medias Deportivas",
    brand: "Under Armour",
    description: "Tecnología anti-olor",
    rating: 5,
  },

  // Colonias & Splash
  {
    id: "colonia-elegante",
    name: "Colonia Elegante 100ml",
    price: 45.0,
    image: "/men-s-cologne-fragrance-bottle-elegant.jpg",
    category: "Colonias & Splash",
    brand: "", // Updated to include brand field
    description: "Fragancias masculinas únicas",
    badge: "Premium",
    rating: 5,
  },
  {
    id: "colonia-hugo-boss-bottled",
    name: "Hugo Boss Bottled 100ml",
    price: 85.0,
    image: "/men-s-cologne-fragrance-bottle-elegant.jpg",
    category: "Colonias & Splash",
    brand: "Hugo Boss",
    description: "Fragancia masculina elegante",
    badge: "Premium",
    rating: 5,
  },
  {
    id: "colonia-carolina-herrera",
    name: "Carolina Herrera 212 100ml",
    price: 78.0,
    image: "/men-s-cologne-fragrance-bottle-elegant.jpg",
    category: "Colonias & Splash",
    brand: "Carolina Herrera",
    description: "Aroma urbano sofisticado",
    rating: 5,
  },
  {
    id: "colonia-paco-rabanne",
    name: "Paco Rabanne 1 Million 100ml",
    price: 82.0,
    image: "/men-s-cologne-fragrance-bottle-elegant.jpg",
    category: "Colonias & Splash",
    brand: "Paco Rabanne",
    description: "Fragancia icónica de éxito",
    badge: "Más Vendido",
    rating: 5,
  },
  {
    id: "splash-axe-signature",
    name: "Axe Signature Body Spray",
    price: 25.0,
    image: "/men-s-cologne-fragrance-bottle-elegant.jpg",
    category: "Colonias & Splash",
    brand: "Axe",
    description: "Frescura duradera",
    badge: "Oferta",
    rating: 4,
  },
];

export const allProductsByCategory: Record<string, Product[]> = {
  "Shorts Deportivos": allProducts.filter(
    (p) => p.category === "Shorts Deportivos"
  ),
  Franelas: allProducts.filter((p) => p.category === "Franelas"),
  Oversize: allProducts.filter((p) => p.category === "Oversize"),
  "Box Fit": allProducts.filter((p) => p.category === "Box Fit"),
  Jeans: allProducts.filter((p) => p.category === "Jeans"),
  "Boxer Interiores": allProducts.filter(
    (p) => p.category === "Boxer Interiores"
  ),
  "Medias Deportivas": allProducts.filter(
    (p) => p.category === "Medias Deportivas"
  ),
  "Colonias & Splash": allProducts.filter(
    (p) => p.category === "Colonias & Splash"
  ),
};

export const categories = [
  {
    name: "Shorts Deportivos",
    icon: Dumbbell,
    description: "Comodidad y estilo para tu entrenamiento",
    image: "/men-s-athletic-shorts-sportswear.jpg",
  },
  {
    name: "Franelas",
    icon: Shirt,
    description: "Básicos esenciales para cada día",
    image: "/men-s-t-shirts-casual-cotton-tees.jpg",
  },
  {
    name: "Oversize",
    icon: Maximize,
    description: "La tendencia urbana del momento",
    image: "/oversized-men-s-streetwear-clothing.jpg",
  },
  {
    name: "Box Fit",
    icon: Box,
    description: "Corte moderno y estructura perfecta",
    image: "/box-fit-men-s-shirt-structured-style.jpg",
  },
  {
    name: "Jeans",
    icon: Scissors,
    description: "Denim de calidad premium",
    image: "/men-s-premium-denim-jeans-blue.jpg",
  },
  {
    name: "Boxer Interiores",
    icon: Layers,
    description: "Comodidad interior excepcional",
    image: "/men-s-boxer-briefs-underwear.jpg",
  },
  {
    name: "Medias Deportivas",
    icon: Footprints,
    description: "Rendimiento y confort",
    image: "/athletic-sports-socks-men-s.jpg",
  },
  {
    name: "Colonias & Splash",
    icon: Droplets,
    description: "Fragancias masculinas únicas",
    image: "/men-s-cologne-fragrance-bottle-elegant.jpg",
  },
];
